filter:
    excluded_paths:
        - 'tests/*'
        - 'vcr/*'
        - 'steam/protobufs/*'
tools:
    external_code_coverage:
        timeout: 300
        runs: 4

build:
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run
