language: python
cache: pip
sudo: false
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - make init
    - pip install coveralls
    - pip install scrutinizer-ocular
script:
    - make test
    - make docs
after_script:
    - coveralls
    - ocular
